import { MovimientoProducto, Producto } from './productos';

export interface Categoria {
  id: number;
  name: string;
  icon: string;
  isEnabled: boolean;
  color?: string;
  ordenCategoria: number;
}
export const DefaultCategories: Categoria[] = [
  {
    id: 1,
    name: 'Compras',
    icon: 'cart-outline',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 2,
    name: 'Alimentos',
    icon: 'silverware-fork-knife',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 3,
    name: 'Telefono',
    icon: 'cellphone',
    isEnabled: true,

    ordenCategoria: 0,
  },
  {
    id: 4,
    name: 'Entretenimiento',
    icon: 'microphone-variant',
    isEnabled: true,

    ordenCategoria: 0,
  },
  {
    id: 5,
    name: 'Educación',
    icon: 'book-open-variant',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 6,
    name: 'Belleza',
    icon: 'face-woman-shimmer-outline',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 7,
    name: 'Deportes',
    icon: 'swim',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 8,
    name: 'Social',
    icon: 'account-multiple',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 9,
    name: 'Transporte',
    icon: 'bus',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 10,
    name: 'Ropa',
    icon: 'tshirt-crew-outline',
    isEnabled: true,

    ordenCategoria: 0,
  },
  {
    id: 11,
    name: 'Auto',
    icon: 'car-outline',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 12,
    name: 'Bebidas',
    icon: 'liquor',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 13,
    name: 'Cigarrillo',
    icon: 'smoking',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 14,
    name: 'Electronicos',
    icon: 'ipod',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 15,
    name: 'Viajes',
    icon: 'airplane',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 16,
    name: 'Salud',
    icon: 'bottle-tonic-plus',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 17,
    name: 'Mascota',
    icon: 'cat',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 18,
    name: 'Reparacion',
    icon: 'tools',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 19,
    name: 'Vivienda',
    icon: 'format-paint',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 20,
    name: 'Hogar',
    icon: 'bookshelf',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 21,
    name: 'Regalo',
    icon: 'gift',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 22,
    name: 'Donar',
    icon: 'hand-heart-outline',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 23,
    name: 'Loteria',
    icon: 'slot-machine',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 24,
    name: 'Bocadillos',
    icon: 'food-croissant',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 25,
    name: 'Hijos',
    icon: 'baby-carriage',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 26,
    name: 'Verduras',
    icon: 'carrot',
    isEnabled: true,
    ordenCategoria: 0,
  },
  {
    id: 27,
    name: 'Frutas',
    icon: 'fruit-grapes-outline',
    isEnabled: true,
    ordenCategoria: 0,
  },
];

export const DefaultProductos: {
  producto: Omit<Producto, 'id' | 'detalle'>;
  movimiento: Omit<MovimientoProducto, 'id' | 'idProducto'>;
}[] = [
  {
    producto: {
      nombre: 'Coca',
      categoria: DefaultCategories[1],
      fechaCreacion: '',
      agregarListaCompra: false,
      cantidadAdvertencia: 3,
      seguirEstadistica: true,
    },
    movimiento: {
      fechaCreacion: '',
      precio: 0,
      cantidad: 3,
      isUnitario: false,
      precioUnitario: 0,
      isVence: false,
      fechaVencimiento: '',
      isCompra: true,
      recordatorio: '',
    },
  },
  {
    producto: {
      nombre: 'Servilletas',
      categoria: DefaultCategories[19],
      fechaCreacion: '',
      agregarListaCompra: false,
      cantidadAdvertencia: 3,
      seguirEstadistica: true,
    },
    movimiento: {
      fechaCreacion: '',
      precio: 0,
      cantidad: 4,
      isUnitario: false,
      precioUnitario: 0,
      isVence: false,
      fechaVencimiento: '',
      isCompra: true,
      recordatorio: '',
    },
  },
  {
    producto: {
      nombre: 'Jabon',
      categoria: DefaultCategories[16],
      fechaCreacion: '',
      agregarListaCompra: false,
      cantidadAdvertencia: 3,
      seguirEstadistica: true,
    },
    movimiento: {
      fechaCreacion: '',
      precio: 0,
      cantidad: 6,
      isUnitario: false,
      precioUnitario: 0,
      isVence: false,
      fechaVencimiento: '',
      isCompra: true,
      recordatorio: '',
    },
  },
  {
    producto: {
      nombre: 'Detergente',
      categoria: DefaultCategories[18],
      fechaCreacion: '',
      agregarListaCompra: false,
      cantidadAdvertencia: 3,
      seguirEstadistica: true,
    },
    movimiento: {
      fechaCreacion: '',
      precio: 0,
      cantidad: 2,
      isUnitario: false,
      precioUnitario: 0,
      isVence: false,
      fechaVencimiento: '',
      isCompra: true,
      recordatorio: '',
    },
  },
  {
    producto: {
      nombre: 'Yerba',
      categoria: DefaultCategories[1],
      fechaCreacion: '',
      agregarListaCompra: false,
      cantidadAdvertencia: 3,
      seguirEstadistica: true,
    },
    movimiento: {
      fechaCreacion: '',
      precio: 0,
      cantidad: 1,
      isUnitario: false,
      precioUnitario: 0,
      isVence: false,
      fechaVencimiento: '',
      isCompra: true,
      recordatorio: '',
    },
  },
  {
    producto: {
      nombre: 'Esponja',
      categoria: DefaultCategories[18],
      fechaCreacion: '',
      agregarListaCompra: false,
      cantidadAdvertencia: 3,
      seguirEstadistica: true,
    },
    movimiento: {
      fechaCreacion: '',
      precio: 0,
      cantidad: 7,
      isUnitario: false,
      precioUnitario: 0,
      isVence: false,
      fechaVencimiento: '',
      isCompra: true,
      recordatorio: '',
    },
  },
  {
    producto: {
      nombre: 'Atún',
      categoria: DefaultCategories[1],
      fechaCreacion: '',
      agregarListaCompra: false,
      cantidadAdvertencia: 3,
      seguirEstadistica: true,
    },
    movimiento: {
      fechaCreacion: '',
      precio: 0,
      cantidad: 5,
      isUnitario: false,
      precioUnitario: 0,
      isVence: false,
      fechaVencimiento: '',
      isCompra: true,
      recordatorio: '',
    },
  },
  {
    producto: {
      nombre: 'Café',
      categoria: DefaultCategories[1],
      fechaCreacion: '',
      agregarListaCompra: false,
      cantidadAdvertencia: 3,
      seguirEstadistica: true,
    },
    movimiento: {
      fechaCreacion: '',
      precio: 0,
      cantidad: 8,
      isUnitario: false,
      precioUnitario: 0,
      isVence: false,
      fechaVencimiento: '',
      isCompra: true,
      recordatorio: '',
    },
  },
  {
    producto: {
      nombre: 'Azucar',
      categoria: DefaultCategories[1],
      fechaCreacion: '',
      agregarListaCompra: false,
      cantidadAdvertencia: 3,
      seguirEstadistica: true,
    },
    movimiento: {
      fechaCreacion: '',
      precio: 0,
      cantidad: 1,
      isUnitario: false,
      precioUnitario: 0,
      isVence: false,
      fechaVencimiento: '',
      isCompra: true,
      recordatorio: '',
    },
  },
  {
    producto: {
      nombre: 'Piedras gato',
      categoria: DefaultCategories[16],
      fechaCreacion: '',
      agregarListaCompra: false,
      cantidadAdvertencia: 3,
      seguirEstadistica: true,
    },
    movimiento: {
      fechaCreacion: '',
      precio: 0,
      cantidad: 9,
      isUnitario: false,
      precioUnitario: 0,
      isVence: false,
      fechaVencimiento: '',
      isCompra: true,
      recordatorio: '',
    },
  },
  {
    producto: {
      nombre: 'Manteca',
      categoria: DefaultCategories[1],
      fechaCreacion: '',
      agregarListaCompra: false,
      cantidadAdvertencia: 3,
      seguirEstadistica: true,
    },
    movimiento: {
      fechaCreacion: '',
      precio: 0,
      cantidad: 2,
      isUnitario: false,
      precioUnitario: 0,
      isVence: false,
      fechaVencimiento: '',
      isCompra: true,
      recordatorio: '',
    },
  },
];
